sudo: required
dist: trusty
language: node_js
node_js:
- "6"
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libarchive-dev curl
- curl http://divvun.no/static_files/zhfsts/se.zhfst  > "etc/sme_NO.zhfst"
- curl http://divvun.no/static_files/zhfsts/smj.zhfst > "etc/smj_NO.zhfst"
- curl http://divvun.no/static_files/zhfsts/sma.zhfst > "etc/sma_NO.zhfst"
- npm i -g npm
notifications:
  email:
    on_success: never
