sudo: required
dist: trusty
language: node_js
node_js:
- "4"
- "6"
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libarchive-dev curl
- cd etc && curl -O http://divvun.no/static_files/zhfsts/se.zhfst 
- cd etc && curl -O http://divvun.no/static_files/zhfsts/smj.zhfst
- cd etc && curl -O http://divvun.no/static_files/zhfsts/sma.zhfst
- npm i -g npm
notifications:
  email:
    on_success: never
